name: build-and-push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: comjustinspicer-web
  BUILD_CONFIGURATION: Release
  ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}
  AdminUser__Email: ${{ secrets.ADMIN_EMAIL }}
  AdminUser__Password: ${{ secrets.ADMIN_PASSWORD }}
  CKEditor__LicenseKey: ${{ secrets.CKEDITOR_LICENSE_KEY }}
  AutoMapper__LicenseKey: ${{ secrets.AUTOMAPPER_LICENSE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c $BUILD_CONFIGURATION

      - name: Test
        run: dotnet test --no-build -c $BUILD_CONFIGURATION --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      #Disabled for now, as not pushing to GHCR
      # - name: Log in to GHCR
      #   if: github.ref == 'refs/heads/master'
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push image
      #   if: github.ref == 'refs/heads/master'
      #   run: |
      #     IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
      #     echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
      #     docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_ID:latest
      #     docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_ID:${{ github.sha }}
      #     docker push $IMAGE_ID:latest
      #     docker push $IMAGE_ID:${{ github.sha }}

      # - name: Summary
      #   run: |
      #     echo "Image pushed: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest" >> $GITHUB_STEP_SUMMARY
